@echo off
setlocal
REM Auto profile runner for Windows.
REM Default = local (smooth localhost:3000). Override example:
REM   set TRANSPORT_PROFILE=remote
REM   run-windows-best.bat

if "%TRANSPORT_PROFILE%"=="" set TRANSPORT_PROFILE=local

set AUDIO_PIPE=%AUDIO_PIPE%
if "%AUDIO_PIPE%"=="" set AUDIO_PIPE=1
set SOUND=%SOUND%
if "%SOUND%"=="" set SOUND=1
set TARGET_FPS=%TARGET_FPS%
if "%TARGET_FPS%"=="" set TARGET_FPS=30
set WS_COMPRESSION=%WS_COMPRESSION%
if "%WS_COMPRESSION%"=="" set WS_COMPRESSION=0
set MAX_UPLOAD_MB=%MAX_UPLOAD_MB%
if "%MAX_UPLOAD_MB%"=="" set MAX_UPLOAD_MB=50
set MAX_USER_STORAGE_MB=%MAX_USER_STORAGE_MB%
if "%MAX_USER_STORAGE_MB%"=="" set MAX_USER_STORAGE_MB=500
set UPLOAD_RETENTION_HOURS=%UPLOAD_RETENTION_HOURS%
if "%UPLOAD_RETENTION_HOURS%"=="" set UPLOAD_RETENTION_HOURS=24
set NO_CLIENT_SHUTDOWN_MS=%NO_CLIENT_SHUTDOWN_MS%
if "%NO_CLIENT_SHUTDOWN_MS%"=="" set NO_CLIENT_SHUTDOWN_MS=5000
set AUDIO_ADAPTIVE_BUFFER=%AUDIO_ADAPTIVE_BUFFER%
if "%AUDIO_ADAPTIVE_BUFFER%"=="" set AUDIO_ADAPTIVE_BUFFER=1
set ADAPTIVE_STREAMING=%ADAPTIVE_STREAMING%
if "%ADAPTIVE_STREAMING%"=="" set ADAPTIVE_STREAMING=1
set ADAPTIVE_LEVELS=%ADAPTIVE_LEVELS%
if "%ADAPTIVE_LEVELS%"=="" set ADAPTIVE_LEVELS=100
set ADAPTIVE_WINDOW_MS=%ADAPTIVE_WINDOW_MS%
if "%ADAPTIVE_WINDOW_MS%"=="" set ADAPTIVE_WINDOW_MS=1000
set ADAPTIVE_RECOVER_WINDOWS=%ADAPTIVE_RECOVER_WINDOWS%
if "%ADAPTIVE_RECOVER_WINDOWS%"=="" set ADAPTIVE_RECOVER_WINDOWS=3

if exist "%~dp0tools\ffmpeg.exe" (
  if "%FFMPEG_PATH%"=="" set FFMPEG_PATH=%~dp0tools\ffmpeg.exe
  if "%AUDIO_CODEC%"=="" set AUDIO_CODEC=opus
) else (
  if "%AUDIO_CODEC%"=="" set AUDIO_CODEC=pcm
)

if /I "%TRANSPORT_PROFILE%"=="remote" (
  set VIDEO_CODEC=%VIDEO_CODEC%
  if "%VIDEO_CODEC%"=="" set VIDEO_CODEC=webp
  set WEBP_QUALITY=%WEBP_QUALITY%
  if "%WEBP_QUALITY%"=="" set WEBP_QUALITY=48
  set WEBP_EFFORT=%WEBP_EFFORT%
  if "%WEBP_EFFORT%"=="" set WEBP_EFFORT=0
  set STREAM_SCALE=%STREAM_SCALE%
  if "%STREAM_SCALE%"=="" set STREAM_SCALE=1
  set MAX_FPS=%MAX_FPS%
  if "%MAX_FPS%"=="" set MAX_FPS=20
  set AUDIO_PACKET_MS=%AUDIO_PACKET_MS%
  if "%AUDIO_PACKET_MS%"=="" set AUDIO_PACKET_MS=60
  set AUDIO_START_BUFFER_MS=%AUDIO_START_BUFFER_MS%
  if "%AUDIO_START_BUFFER_MS%"=="" set AUDIO_START_BUFFER_MS=180
  set CLIENT_AUDIO_MIN_BUFFER_MS=%CLIENT_AUDIO_MIN_BUFFER_MS%
  if "%CLIENT_AUDIO_MIN_BUFFER_MS%"=="" set CLIENT_AUDIO_MIN_BUFFER_MS=120
  set CLIENT_AUDIO_MAX_BUFFER_MS=%CLIENT_AUDIO_MAX_BUFFER_MS%
  if "%CLIENT_AUDIO_MAX_BUFFER_MS%"=="" set CLIENT_AUDIO_MAX_BUFFER_MS=420
  set OPUS_BITRATE=%OPUS_BITRATE%
  if "%OPUS_BITRATE%"=="" set OPUS_BITRATE=64k
) else (
  REM localhost / LAN same-machine: ưu tiên audio ổn định và CPU nhẹ
  set VIDEO_CODEC=%VIDEO_CODEC%
  if "%VIDEO_CODEC%"=="" set VIDEO_CODEC=rgb565
  set STREAM_SCALE=%STREAM_SCALE%
  if "%STREAM_SCALE%"=="" set STREAM_SCALE=1
  set MAX_FPS=%MAX_FPS%
  if "%MAX_FPS%"=="" set MAX_FPS=30
  set AUDIO_PACKET_MS=%AUDIO_PACKET_MS%
  if "%AUDIO_PACKET_MS%"=="" set AUDIO_PACKET_MS=40
  set AUDIO_START_BUFFER_MS=%AUDIO_START_BUFFER_MS%
  if "%AUDIO_START_BUFFER_MS%"=="" set AUDIO_START_BUFFER_MS=110
  set CLIENT_AUDIO_MIN_BUFFER_MS=%CLIENT_AUDIO_MIN_BUFFER_MS%
  if "%CLIENT_AUDIO_MIN_BUFFER_MS%"=="" set CLIENT_AUDIO_MIN_BUFFER_MS=70
  set CLIENT_AUDIO_MAX_BUFFER_MS=%CLIENT_AUDIO_MAX_BUFFER_MS%
  if "%CLIENT_AUDIO_MAX_BUFFER_MS%"=="" set CLIENT_AUDIO_MAX_BUFFER_MS=260
  set OPUS_BITRATE=%OPUS_BITRATE%
  if "%OPUS_BITRATE%"=="" set OPUS_BITRATE=96k
)

node -e "require('sharp')" >nul 2>nul
if errorlevel 1 (
  echo sharp is not installed. Installing sharp...
  npm install sharp
)

echo [run] TRANSPORT_PROFILE=%TRANSPORT_PROFILE% ADAPTIVE_STREAMING=%ADAPTIVE_STREAMING% ADAPTIVE_LEVELS=%ADAPTIVE_LEVELS% VIDEO_CODEC=%VIDEO_CODEC% AUDIO_CODEC=%AUDIO_CODEC% MAX_FPS=%MAX_FPS% AUDIO_PACKET_MS=%AUDIO_PACKET_MS%
node server.js
